const DRILLS=[
{title:"Form Shooting",cat:"Shooting",level:"Beginner",emoji:"🎯",desc:"Slow, controlled makes from close range."},
{title:"5-Spot Shooting",cat:"Shooting",level:"Intermediate",emoji:"🏀",desc:"Hit each spot and track your makes."},
{title:"Two-Ball Pounds",cat:"Ball Handling",level:"Intermediate",emoji:"⚡",desc:"Control both balls with quick, low dribbles."},
{title:"Cone Crossovers",cat:"Ball Handling",level:"Beginner",emoji:"🔀",desc:"Attack each cone with sharp changes of direction."},
{title:"Mikan Drill",cat:"Finishing",level:"Beginner",emoji:"🧺",desc:"Build touch and finishing around the rim."},
{title:"Euro Step Series",cat:"Finishing",level:"Advanced",emoji:"🔥",desc:"Practice controlled two-foot finishes."},
{title:"Defensive Slides",cat:"Defense",level:"Beginner",emoji:"🛡️",desc:"Stay low and move without crossing your feet."}
];
let posts=[
{id:1,user:"Isaac",handle:"@isaac",caption:"Shooting workout today. 100 shots. 🔥",type:"video",likes:24,comments:6,liked:false},
{id:2,user:"Jaylen",handle:"@jay_ball",caption:"Finishing drills — left hand only. 💪",type:"video",likes:18,comments:4,liked:false},
{id:3,user:"Mason",handle:"@masonb23",caption:"Big win tonight! 🏆",type:"game",likes:31,comments:7,liked:false}
];
let selectedMedia=null,postType="Workout";
const app=document.getElementById("app");
function showToast(msg){let t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),1800)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function media(p){return p.url?`<div class="media"><video controls playsinline src="${p.url}"></video></div>`:`<div class="media"><div class="media-placeholder">${p.type==="game"?"🏆":"▶️"}</div></div>`}
function card(p){return `<article class="post"><div class="post-head"><div class="avatar">${p.user[0]}</div><div><b>${esc(p.user)}</b><div class="muted">${esc(p.handle)} · today</div></div></div><p class="caption">${esc(p.caption)}</p>${media(p)}<div class="actions"><button class="action ${p.liked?"liked":""}" onclick="toggleLike(${p.id})">♥ ${p.likes}</button><button class="action" onclick="showToast('Comments will connect with accounts')">💬 ${p.comments}</button><button class="action" onclick="showToast('Sharing will connect with accounts')">↗ Share</button></div></article>`}
function drill(d){return `<div class="card drill-card"><div class="drill-icon">${d.emoji}</div><div><h4>${esc(d.title)}</h4><p>${esc(d.cat)} · ${esc(d.level)}</p><p>${esc(d.desc)}</p></div></div>`}
function randomDrill(){let d=DRILLS[Math.floor(Math.random()*DRILLS.length)];app.innerHTML=`<h1 class="title">Your Drill 🔥</h1><p class="sub">Something to work on right now.</p>${drill(d)}<button class="btn" onclick="randomDrill()">🎲 New Drill</button><button class="btn secondary" onclick="show('discover')">Back</button>`}
function show(s){
document.querySelectorAll(".bottom-nav button[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===s));
if(s==="home")app.innerHTML=`<h1 class="title">For You</h1><div class="tabs"><button class="pill active">For You</button><button class="pill" onclick="show('friends')">Friends</button><button class="pill" onclick="randomDrill()">🏀 Drill</button></div><div class="section-row"><h3>Friends</h3><button class="link-btn" onclick="show('friends')">See all</button></div>${posts.map(card).join("")}<div class="section-row"><h3>Drill of the Day</h3><button class="link-btn" onclick="randomDrill()">New drill</button></div>${drill(DRILLS[0])}`;
if(s==="discover")app.innerHTML=`<h1 class="title">Discover</h1><p class="sub">Find workouts, drills and ideas.</p><input class="input" placeholder="Search drills..." oninput="filterDrills(this.value)"><div class="tabs"><button class="pill active" onclick="filterCategory('All')">All</button>${["Shooting","Ball Handling","Finishing","Defense"].map(c=>`<button class="pill" onclick="filterCategory('${c}')">${c}</button>`).join("")}</div><div id="drillList">${DRILLS.map(drill).join("")}</div><button class="btn" onclick="randomDrill()">🎲 Give Me a Random Drill</button>`;
if(s==="friends")app.innerHTML=`<h1 class="title">Friends</h1><p class="sub">Your basketball crew.</p><div class="card">${["Jaylen","Liam","Mason","Noah","Ethan"].map((n,i)=>`<div class="friend"><div class="avatar">${n[0]}</div><div class="friend-info"><b>${n}</b><div class="muted">@${n.toLowerCase()}hoops</div></div><span class="badge">${i%2?"Online":"Training"}</span></div>`).join("")}</div><button class="btn" onclick="showToast('Friend search will connect to accounts next')">＋ Find Friends</button>`;
if(s==="profile")app.innerHTML=`<div class="profile"><div class="avatar big">I</div><h1>Isaac</h1><p class="muted">@isaac</p><p class="bio">Locked in. Always getting better. 🏀</p></div><div class="grid"><div class="stat"><b>3</b><span>Posts</span></div><div class="stat"><b>5</b><span>Friends</span></div><div class="stat"><b>4</b><span>Workouts</span></div><div class="stat"><b>2</b><span>Challenges</span></div></div><div class="section-row"><h3>Training streak</h3></div><div class="card"><b>4 days</b><div class="progress"><span></span></div></div>${posts.filter(p=>p.user==="Isaac").map(card).join("")}`;
if(s==="create")post();
}
function post(){app.innerHTML=`<h1 class="title">Create</h1><p class="sub">Share what you're working on.</p><div class="card"><div class="tabs"><button class="pill active" onclick="setType('Workout',this)">💪 Workout</button><button class="pill" onclick="setType('Game',this)">🏀 Game</button><button class="pill" onclick="setType('Post',this)">📸 Post</button></div><input id="mediaInput" class="input" type="file" accept="video/*,image/*"><div id="preview" class="file-preview"></div><textarea id="caption" class="textarea" placeholder="What are you working on?"></textarea><button class="btn" onclick="createPost()">Post to CLUTCH</button></div>`;document.getElementById("mediaInput").addEventListener("change",handleFile)}
function setType(t,e){postType=t;document.querySelectorAll(".tabs .pill").forEach(x=>x.classList.remove("active"));e.classList.add("active")}
function handleFile(e){let f=e.target.files[0];if(!f)return;selectedMedia={url:URL.createObjectURL(f),type:f.type};let p=document.getElementById("preview");p.style.display="block";p.innerHTML=f.type.startsWith("video/")?`<video controls playsinline src="${selectedMedia.url}"></video>`:`<img src="${selectedMedia.url}">`}
function createPost(){let c=document.getElementById("caption").value.trim();if(!c&&!selectedMedia){showToast("Add a photo/video or caption first");return}posts.unshift({id:Date.now(),user:"Isaac",handle:"@isaac",caption:c||"New workout post 🔥",type:postType==="Game"?"game":"video",likes:0,comments:0,liked:false,url:selectedMedia?.url});selectedMedia=null;show("home");showToast("Post added to your feed")}
function toggleLike(id){let p=posts.find(x=>x.id===id);if(!p)return;p.liked=!p.liked;p.likes+=p.liked?1:-1;show("home")}
function filterCategory(c){let a=c==="All"?DRILLS:DRILLS.filter(d=>d.cat===c);document.getElementById("drillList").innerHTML=a.map(drill).join("")}
function filterDrills(q){q=q.toLowerCase();document.getElementById("drillList").innerHTML=DRILLS.filter(d=>(d.title+d.cat+d.desc).toLowerCase().includes(q)).map(drill).join("")||'<div class="empty">No drills found.</div>'}
window.show=show;window.post=post;window.randomDrill=randomDrill;window.setType=setType;window.handleFile=handleFile;window.createPost=createPost;window.toggleLike=toggleLike;window.filterCategory=filterCategory;window.filterDrills=filterDrills;window.showToast=showToast;
show("home");